name: "Terraform plan and apply"

on:
  workflow_dispatch:
#  push:
#     branches:
#            - main

jobs:
  deploy:
         runs-on: "ubuntu-latest"

         steps:
           - name: Clone terraform code
             uses: actions/checkout@v2
             with:
               repository: jitenderyadavofc/terraform-infra
               ref: main
               path: terraform-code

           - name: copy all files
             run: cp config.auto.tfvars terraform-code/

           - name: setup terraform
             uses: hashicorp/setup-terraform@v1
             with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

           - name: Terraform Init
             id: init
             run: terraform init terraform-code

           - name: Terraform plan
             id: plan
 #            if: github.event_name == 'push'
             run: terraform plan -var-file=terraform-code/*.tfvars  terraform-code   

           - name: Terraform apply
             id: apply
    #         if: github.event_name == 'push'
             run: terraform apply -auto-approve  -var-file=terraform-code/*.tfvars  terraform-code      
